In [1]:
# --------------------------- [Module Imports] -------------------------
import numpy as np

In [2]:
# --------------------------- [Scoring Scheme] -------------------------
reward_match = 4
penalty_mismatch = -1
penalty_gap = -5

In [3]:
# --------------------------- [Input Sequences] -------------------------
seq1 = "VAEGEWGVAA"
seq2 = "REWVAEA"

aligned_seq1 = ""
aligned_seq2 = ""

In [4]:
print(seq1)
print(seq2)

VAEGEWGVAA
REWVAEA


In [5]:

# --------------------------- [Matrix Initialization] -------------------------
match_matrix = np.zeros((len(seq1), len(seq2)))
score_matrix = np.zeros((len(seq1)+1, len(seq2)+1))

# For match_matrix
for i in range(len(seq1)):
    for j in range(len(seq2)):
        if(seq1[i]==seq2[j]):
            match_matrix[i][j] = reward_match
        else:
            match_matrix[i][j] = penalty_mismatch
            
# For score_matrix
for i in range(len(seq1)+1):
    score_matrix[i][0] = max(0, i*penalty_gap)

for j in range(len(seq2)+1):
    score_matrix[0][j] = max(0, j*penalty_gap)
    

In [6]:
print(match_matrix)
print(score_matrix)

[[-1. -1. -1.  4. -1. -1. -1.]
 [-1. -1. -1. -1.  4. -1.  4.]
 [-1.  4. -1. -1. -1.  4. -1.]
 [-1. -1. -1. -1. -1. -1. -1.]
 [-1.  4. -1. -1. -1.  4. -1.]
 [-1. -1.  4. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1.  4. -1. -1. -1.]
 [-1. -1. -1. -1.  4. -1.  4.]
 [-1. -1. -1. -1.  4. -1.  4.]]
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [7]:
# --------------------------- [Fill Score Matrix] -------------------------
for i in range(1, len(seq1)+1):
    for j in range(1, len(seq2)+1):
        score_matrix[i][j] = max(
            score_matrix[i-1][j-1] + match_matrix[i-1][j-1],
            score_matrix[i-1][j] + penalty_gap,
            score_matrix[i][j-1] + penalty_gap,
        )
        

In [8]:
print(score_matrix)

[[ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. -1. -1. -1.  4. -1. -1. -1.]
 [ 0. -1. -2. -2. -1.  8.  3.  3.]
 [ 0. -1.  3. -2. -3.  3. 12.  7.]
 [ 0. -1. -2.  2. -3. -2.  7. 11.]
 [ 0. -1.  3. -2.  1. -4.  2.  6.]
 [ 0. -1. -2.  7.  2.  0. -3.  1.]
 [ 0. -1. -2.  2.  6.  1. -1. -4.]
 [ 0. -1. -2. -3.  6.  5.  0. -2.]
 [ 0. -1. -2. -3.  1. 10.  5.  4.]
 [ 0. -1. -2. -3. -4.  5.  9.  9.]]


In [9]:
# --------------------------- [Find Max ii and jj] -------------------------
ii = 0
jj = len(seq2)

score = score_matrix[ii][jj]

for i in range(0, len(seq1)+1):
    if (score_matrix[i][len(seq2)]>score):
        score = score_matrix[i][len(seq2)]
        ii = i
        jj = len(seq2)

for j in range(0, len(seq2)+1):
    if (score_matrix[len(seq1)][j]>score):
        score = score_matrix[len(seq1)][j]
        ii = len(seq1)
        jj = j

In [10]:
print(ii)
print(jj)

4
7


In [11]:
# --------------------------- [Print Alignment and Score] -------------------------
temp_i = ii
temp_j = jj

while not (ii==0 or jj==0):
    if (ii>0 and jj>0 and score_matrix[ii][jj] == score_matrix[ii-1][jj-1] + match_matrix[ii-1][jj-1]):
        aligned_seq1 = seq1[ii-1] + aligned_seq1
        aligned_seq2 = seq2[jj-1] + aligned_seq2
        ii -= 1
        jj -= 1
    
    elif (ii>0 and score_matrix[ii][jj] == score_matrix[ii-1][jj] + penalty_gap):
        aligned_seq1 = seq1[ii-1] + aligned_seq1
        aligned_seq2 = "-" + aligned_seq2
        ii -= 1
    
    else:
        aligned_seq1 = "-" + aligned_seq1
        aligned_seq2 = seq2[jj-1] + aligned_seq2
        jj -= 1

while(ii!=0):
    aligned_seq1 =  seq1[ii-1] + aligned_seq1
    aligned_seq2 = "-" + aligned_seq2 
    ii -= 1
    
while(jj!=0):
    aligned_seq1 = "-" + aligned_seq1 
    aligned_seq2 =  seq2[jj-1] + aligned_seq2    
    jj -= 1

ii = temp_i
jj = temp_j
if (jj == len(seq2)):
    while (ii!=len(seq1)+1):
        aligned_seq1 = aligned_seq1 + seq1[ii-1]
        aligned_seq2 = aligned_seq2 + "-"
        ii += 1
else:
    while (jj!=len(seq2)+1):
        aligned_seq1 = aligned_seq1 + "-"
        aligned_seq2 = aligned_seq2 + seq2[jj-1]
        jj += 1

In [12]:
print(score)
print(aligned_seq1)
print(aligned_seq2)

11.0
---VAEGGEWGVAA
REWVAEA-------
