In [44]:
# --------------------------- [Module Imports] -------------------------
import numpy as np

In [45]:
# --------------------------- [Scoring Scheme] -------------------------
reward_match = 2
penalty_mismatch = -1
penalty_gap = -1

In [46]:
# --------------------------- [Input Sequences] -------------------------
seq1 = "ACCTATC"
seq2 = "ACCGGTAT"

aligned_seq1 = ""
aligned_seq2 = ""

In [47]:
print(seq1)
print(seq2)

ACCTATC
ACCGGTAT


In [48]:
# --------------------------- [Matrix Initialization] -------------------------
match_matrix = np.zeros((len(seq1), len(seq2)))
score_matrix = np.zeros((len(seq1)+1, len(seq2)+1))

# For match_matrix
for i in range(len(seq1)):
    for j in range(len(seq2)):
        if(seq1[i]==seq2[j]):
            match_matrix[i][j] = reward_match
        else:
            match_matrix[i][j] = penalty_mismatch
            
# For score_matrix
for i in range(len(seq1)+1):
    score_matrix[i][0] = i*penalty_gap

for j in range(len(seq2)+1):
    score_matrix[0][j] = j*penalty_gap
  

In [49]:
print(match_matrix)
print(score_matrix)

[[ 2. -1. -1. -1. -1. -1.  2. -1.]
 [-1.  2.  2. -1. -1. -1. -1. -1.]
 [-1.  2.  2. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.  2. -1.  2.]
 [ 2. -1. -1. -1. -1. -1.  2. -1.]
 [-1. -1. -1. -1. -1.  2. -1.  2.]
 [-1.  2.  2. -1. -1. -1. -1. -1.]]
[[ 0. -1. -2. -3. -4. -5. -6. -7. -8.]
 [-1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [-2.  0.  0.  0.  0.  0.  0.  0.  0.]
 [-3.  0.  0.  0.  0.  0.  0.  0.  0.]
 [-4.  0.  0.  0.  0.  0.  0.  0.  0.]
 [-5.  0.  0.  0.  0.  0.  0.  0.  0.]
 [-6.  0.  0.  0.  0.  0.  0.  0.  0.]
 [-7.  0.  0.  0.  0.  0.  0.  0.  0.]]


In [50]:
# --------------------------- [Fill Score Matrix] -------------------------
for i in range(1, len(seq1)+1):
    for j in range(1, len(seq2)+1):
        score_matrix[i][j] = max(
            score_matrix[i-1][j-1] + match_matrix[i-1][j-1],
            score_matrix[i-1][j] + penalty_gap,
            score_matrix[i][j-1] + penalty_gap
        )

In [51]:
print(score_matrix)

[[ 0. -1. -2. -3. -4. -5. -6. -7. -8.]
 [-1.  2.  1.  0. -1. -2. -3. -4. -5.]
 [-2.  1.  4.  3.  2.  1.  0. -1. -2.]
 [-3.  0.  3.  6.  5.  4.  3.  2.  1.]
 [-4. -1.  2.  5.  5.  4.  6.  5.  4.]
 [-5. -2.  1.  4.  4.  4.  5.  8.  7.]
 [-6. -3.  0.  3.  3.  3.  6.  7. 10.]
 [-7. -4. -1.  2.  2.  2.  5.  6.  9.]]


In [52]:
# --------------------------- [Print Alignment and Score] -------------------------
ii = len(seq1)
jj = len(seq2)

score = score_matrix[ii][jj]

while not (ii==0 and jj==0):
    if (ii>0 and jj>0 and score_matrix[ii][jj] == score_matrix[ii-1][jj-1] + match_matrix[ii-1][jj-1]):
        aligned_seq1 = seq1[ii-1] + aligned_seq1
        aligned_seq2 = seq2[jj-1] + aligned_seq2
        ii -= 1
        jj -= 1
    
    elif (ii>0 and score_matrix[ii][jj] == score_matrix[ii-1][jj] + penalty_gap):
        aligned_seq1 = seq1[ii-1] + aligned_seq1
        aligned_seq2 = "-" + aligned_seq2
        ii -= 1
    
    else:
        aligned_seq1 = "-" + aligned_seq1
        aligned_seq2 = seq2[jj-1] + aligned_seq2
        jj -= 1
        

In [53]:
print(score)
print(aligned_seq1)
print(aligned_seq2)

9.0
ACC--TATC
ACCGGTAT-
