In [16]:
# --------------------------- [Module Imports] -------------------------
import numpy as np

In [17]:
# --------------------------- [Scoring Scheme] -------------------------
reward_match = 2
penalty_mismatch = -1
penalty_gap = -1

In [18]:
# --------------------------- [Input Sequences] -------------------------
seq1 = "TTGTATC"
seq2 = "ACCGGTAT"

aligned_seq1 = ""
aligned_seq2 = ""

In [19]:
print(seq1)
print(seq2)

TTGTATC
ACCGGTAT


In [20]:

# --------------------------- [Matrix Initialization] -------------------------
match_matrix = np.zeros((len(seq1), len(seq2)))
score_matrix = np.zeros((len(seq1)+1, len(seq2)+1))

# For match_matrix
for i in range(len(seq1)):
    for j in range(len(seq2)):
        if(seq1[i]==seq2[j]):
            match_matrix[i][j] = reward_match
        else:
            match_matrix[i][j] = penalty_mismatch
            
# For score_matrix
for i in range(len(seq1)+1):
    score_matrix[i][0] = max(0, i*penalty_gap)

for j in range(len(seq2)+1):
    score_matrix[0][j] = max(0, j*penalty_gap)
    

In [21]:
print(match_matrix)
print(score_matrix)

[[-1. -1. -1. -1. -1.  2. -1.  2.]
 [-1. -1. -1. -1. -1.  2. -1.  2.]
 [-1. -1. -1.  2.  2. -1. -1. -1.]
 [-1. -1. -1. -1. -1.  2. -1.  2.]
 [ 2. -1. -1. -1. -1. -1.  2. -1.]
 [-1. -1. -1. -1. -1.  2. -1.  2.]
 [-1.  2.  2. -1. -1. -1. -1. -1.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [22]:
# --------------------------- [Fill Score Matrix] -------------------------
for i in range(1, len(seq1)+1):
    for j in range(1, len(seq2)+1):
        score_matrix[i][j] = max(
            0,
            score_matrix[i-1][j-1] + match_matrix[i-1][j-1],
            score_matrix[i-1][j] + penalty_gap,
            score_matrix[i][j-1] + penalty_gap,
        )

In [23]:
print(score_matrix)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 2. 1. 2.]
 [0. 0. 0. 0. 0. 0. 2. 1. 3.]
 [0. 0. 0. 0. 2. 2. 1. 1. 2.]
 [0. 0. 0. 0. 1. 1. 4. 3. 3.]
 [0. 2. 1. 0. 0. 0. 3. 6. 5.]
 [0. 1. 1. 0. 0. 0. 2. 5. 8.]
 [0. 0. 3. 3. 2. 1. 1. 4. 7.]]


In [24]:
# --------------------------- [Find Max ii and jj] -------------------------
ii = 0
jj = 0

score = score_matrix[ii][jj]

for i in range(0, len(seq1)+1):
    for j in range(0, len(seq2)+1):
        if (score_matrix[i][j]>score):
           score = score_matrix[i][j]
           ii = i
           jj = j


In [25]:
print(ii)
print(jj)

6
8


In [26]:
# --------------------------- [Print Alignment and Score] -------------------------
while (score_matrix[ii][jj]>0):
    aligned_seq1 = seq1[ii-1] + aligned_seq1
    aligned_seq2 = seq2[jj-1] + aligned_seq2
    ii -= 1
    jj -= 1

In [27]:
print(score)
print(aligned_seq1)
print(aligned_seq2)

8.0
GTAT
GTAT
